### PR TITLE
Account info bug fixes

### LINKED ISSUE #116: Account Ignores Empty Required Fields - Save Issues
### Bug summary:
Not sure what else to call this bug. This bug occurs when a user passes OAuth and is brought to the account creation modal, then the page is refreshed, then the user logs in again. The user is marked as saved and complete and allowed to access the board.

There is a second bug. Settings menu does not enforce required fields and _saves all changes when clicking close_. 

### Bug details:
- User is saved upon refresh without clicking "Sign Up"
- Required fields are not required/verified upon refresh
- User can "login" without completing the login process
- Edit-mode in Settings menu can be closed without filling in the empty required fields

Feel free to add more bullets upon discovery if applicable.

### PR DESCRIPTION
**Pull request by LokiFrostGiant**
## Tickets
Closes #116 
## Summary Of Changes
Fixes two bugs related to Account information.
- Accounts now **must** have all required fields filled to view the Kanban
- If user changes info in the Edit Account Info Modal but closes without saving, the unsaved changes are discarded.
## Notes for Reviewers
- My js might be "sub-optimal" in some places, so feel free to teach me.

### CODE REVIEW

File: frontend/src/components/modal/user/UserInfoModal.vue [hunk 1]
```diff
@@ -263,6 +260,10 @@ export default {
         this.editingEnabled = true
       }
     },
+    safeClose() {
+      this.userData = { ...this.initialData }
```
Comment (jaredwebber) [inline frontend/src/components/modal/user/UserInfoModal.vue:264]: From my testing it looks like this (along with the `initialData` field) isn't required, since userData is a deep copy

File: frontend/src/views/MainView.vue [hunk 2]
```diff
@@ -67,11 +67,21 @@ export default {
   methods: {
     userSignedIn(resp) {
       this.userData = resp.data
-      if (resp.created) {
+      if (resp.created || this.setupIncomplete()) {
```
Comment (jaredwebber) [inline frontend/src/views/MainView.vue:70]: I'm seeing the MainView `doesnt open setupModal when created is false` test failing with this new addition

**Review by jaredwebber — DISMISSED** [review]
Just a couple notes - also curious if @Speuce or @drkitt think its worth removing the `created` flag which is returned with `get_or_create_user` since it's somewhat redundant now

File: frontend/src/components/modal/user/UserInfoModal.vue (hunk 1 above)
Comment (LokiFrostGiant) [reply frontend/src/components/modal/user/UserInfoModal.vue:264]: Confirmed unneeded now due to the userData deep copy resolution. Reverting.

**Review by drkitt — APPROVED** [review]
LGTM! @jaredwebber I think it would be nice to remove the `created` flag, but only if it's as easy as it looks (i.e. change backend return value, change frontend condition check, spend a couple minutes updating tests). If it turns out to be non-trivial, I think we can keep it as-is.

**Comment by jaredwebber** [comment]
@LokiFrostGiant don't worry about removing the `created` field, I'll get rid of it in #121 since I'll be returning a different value from the same endpoint

**Comment by LokiFrostGiant** [comment]
sounds good @jaredwebber ! Merging and deleting.
